// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/act3-ai/gnoci/internal/progress (interfaces: Evaluator)
//
// Generated by this command:
//
//	mockgen -typed -package progressmock -destination ./progressmock/progressmock.gen.go github.com/act3-ai/gnoci/internal/progress Evaluator
//

// Package progressmock is a generated GoMock package.
package progressmock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEvaluator is a mock of Evaluator interface.
type MockEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockEvaluatorMockRecorder
	isgomock struct{}
}

// MockEvaluatorMockRecorder is the mock recorder for MockEvaluator.
type MockEvaluatorMockRecorder struct {
	mock *MockEvaluator
}

// NewMockEvaluator creates a new mock instance.
func NewMockEvaluator(ctrl *gomock.Controller) *MockEvaluator {
	mock := &MockEvaluator{ctrl: ctrl}
	mock.recorder = &MockEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvaluator) EXPECT() *MockEvaluatorMockRecorder {
	return m.recorder
}

// Progress mocks base method.
func (m *MockEvaluator) Progress() (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Progress")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Progress indicates an expected call of Progress.
func (mr *MockEvaluatorMockRecorder) Progress() *MockEvaluatorProgressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*MockEvaluator)(nil).Progress))
	return &MockEvaluatorProgressCall{Call: call}
}

// MockEvaluatorProgressCall wrap *gomock.Call
type MockEvaluatorProgressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEvaluatorProgressCall) Return(arg0, arg1 int, arg2 error) *MockEvaluatorProgressCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEvaluatorProgressCall) Do(f func() (int, int, error)) *MockEvaluatorProgressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEvaluatorProgressCall) DoAndReturn(f func() (int, int, error)) *MockEvaluatorProgressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
