// Code generated by MockGen. DO NOT EDIT.
// Source: io (interfaces: ReadCloser)
//
// Generated by this command:
//
//	mockgen -typed -package iomock -destination ./iomock.gen.go io ReadCloser
//

// Package iomock is a generated GoMock package.
package iomock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReadCloser is a mock of ReadCloser interface.
type MockReadCloser struct {
	ctrl     *gomock.Controller
	recorder *MockReadCloserMockRecorder
	isgomock struct{}
}

// MockReadCloserMockRecorder is the mock recorder for MockReadCloser.
type MockReadCloserMockRecorder struct {
	mock *MockReadCloser
}

// NewMockReadCloser creates a new mock instance.
func NewMockReadCloser(ctrl *gomock.Controller) *MockReadCloser {
	mock := &MockReadCloser{ctrl: ctrl}
	mock.recorder = &MockReadCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadCloser) EXPECT() *MockReadCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockReadCloserMockRecorder) Close() *MockReadCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReadCloser)(nil).Close))
	return &MockReadCloserCloseCall{Call: call}
}

// MockReadCloserCloseCall wrap *gomock.Call
type MockReadCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadCloserCloseCall) Return(arg0 error) *MockReadCloserCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadCloserCloseCall) Do(f func() error) *MockReadCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadCloserCloseCall) DoAndReturn(f func() error) *MockReadCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockReadCloser) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReadCloserMockRecorder) Read(p any) *MockReadCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadCloser)(nil).Read), p)
	return &MockReadCloserReadCall{Call: call}
}

// MockReadCloserReadCall wrap *gomock.Call
type MockReadCloserReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadCloserReadCall) Return(n int, err error) *MockReadCloserReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadCloserReadCall) Do(f func([]byte) (int, error)) *MockReadCloserReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadCloserReadCall) DoAndReturn(f func([]byte) (int, error)) *MockReadCloserReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
